# Generated by Django 5.1.4 on 2025-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
